#!/usr/bin/bash

set -e

if tput setaf 0 &>/dev/null; then
        ALL_OFF="$(tput sgr0)"
        BOLD="$(tput bold)"
        BLUE="${BOLD}$(tput setaf 4)"
        GREEN="${BOLD}$(tput setaf 2)"
        RED="${BOLD}$(tput setaf 1)"
        YELLOW="${BOLD}$(tput setaf 3)"
else
        ALL_OFF="\e[1;0m"
        BOLD="\e[1;1m"
        BLUE="${BOLD}\e[1;34m"
        GREEN="${BOLD}\e[1;32m"
        RED="${BOLD}\e[1;31m"
        YELLOW="${BOLD}\e[1;33m"
fi

msg() {
        local mesg=${1}; shift
        printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "${@}" >&2
}

## To create a new chroot:
# mkarchroot -C /etc/pacman.conf -M /etc/makepkg.conf /var/lib/build/root base-devel

# set variables
CHROOT="/var/lib/build"

msg "refreshing ${CHROOT}/root"
sudo arch-nspawn ${CHROOT}/root pacman -Syu
